const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const {chromium}=require(path.join(process.env.USERPROFILE,'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));
const root='http://127.0.0.1:8766/prototypes/ticketing/manager.html';const out=path.resolve('docs/audit/preview');fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{for(const width of [1440,390]){
 const page=await browser.newPage({viewport:{width,height:1000},reducedMotion:'reduce'});const errors=[];const external=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!r.url().startsWith('http://127.0.0.1:8766'))external.push(r.url());});
 await page.goto(root);await page.evaluate(()=>document.fonts.ready);await page.screenshot({path:path.join(out,`manager-events-${width}.png`),fullPage:true});
 await page.getByRole('searchbox',{name:'Events suchen'}).fill('Brauhaus');assert.equal(await page.locator('#event-rows tr').count(),1);await page.getByRole('searchbox',{name:'Events suchen'}).fill('');
 await page.locator('a[href="#event/lette/edit"]').click();await page.locator('#event-form').waitFor();
 await page.screenshot({path:path.join(out,`manager-editor-${width}.png`),fullPage:true});
 await page.locator('[data-ticket="six"]').click();await page.getByLabel('Preis pro Ticket').fill('50');await page.locator('#dialog-form button[type="submit"], #dialog-form .dialog-foot .primary').click();
 let db=await page.evaluate(()=>JSON.parse(localStorage.getItem('kk-ticketing-manager-demo-v1')));assert.equal(db.events[0].tickets[0].price,5000);
 await page.getByRole('button',{name:'+ Bundle',exact:true}).click();await page.getByLabel('Bundle-Name').fill('Doppelrunde');await page.getByLabel('6er Teamtisch', {exact:true}).fill('1');await page.getByLabel('4er Teamtisch',{exact:true}).fill('1');await page.locator('.dialog-foot .primary').click();
 await page.locator('.event-head [data-action="duplicate"]').click();await page.getByLabel('Neuer Eventname').fill('Lette – November');await page.getByLabel('Neuer Termin').fill('2026-11-12');await page.screenshot({path:path.join(out,`manager-duplicate-${width}.png`),fullPage:true});await page.getByRole('button',{name:'Als Entwurf duplizieren'}).click();await page.getByRole('heading',{name:'Lette – November',exact:true}).waitFor();
 db=await page.evaluate(()=>JSON.parse(localStorage.getItem('kk-ticketing-manager-demo-v1')));const copy=db.events.find(e=>e.title==='Lette – November');assert.equal(copy.status,'draft');assert.equal(copy.date,'2026-11-12');assert.equal(copy.saleStart,'');assert.equal(db.orders.filter(o=>o.eventId===copy.id).length,0);assert.equal(db.waiters.filter(w=>w.eventId===copy.id).length,0);assert.notEqual(copy.tickets[0].id,db.events[0].tickets[0].id);assert.equal(copy.groups[0].ticketIds[0],copy.tickets[0].id);assert.equal(copy.bundles[0].items[0].ticketId,copy.tickets[0].id);
 await page.getByRole('button',{name:'Veröffentlichen',exact:true}).click();assert.match(await page.locator('#toast').innerText(),/veröffentlicht/);
 await page.reload();await page.locator('#event-form').waitFor();assert.equal(await page.getByLabel('Eventname').inputValue(),'Lette – November');
 await page.getByRole('link',{name:'Bestellungen & Einlass',exact:true}).click();await page.locator('#content [data-action="order"]').click();await page.getByLabel('Name *',{exact:true}).fill('Demo Person');await page.getByLabel('E-Mail *',{exact:true}).fill('demo@example.invalid');await page.getByLabel('Teamname · optional',{exact:true}).fill('Neue Köpfe');await page.locator('.dialog-foot .primary').click();
 assert.match(await page.locator('#order-rows').innerText(),/Neue Köpfe/);await page.getByRole('button',{name:'Einchecken',exact:true}).click();assert.match(await page.locator('#order-rows').innerText(),/Vor Ort/);
 const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Einlassliste exportieren'}).click();const download=await downloadPromise;assert.equal(download.suggestedFilename(),'einlassliste-demo.csv');
 for(const name of ['Überblick','Auswertungen','Warteliste','E-Mails & Reminder','Bestätigung & Ticket','Buchungsformular','Quizvorbereitung']){await page.getByRole('link',{name,exact:true}).click();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`${name}: viewport overflow`);}
 await page.getByRole('button',{name:'Alle Teams übernehmen'}).click();assert.match(await page.locator('#content').innerText(),/Übernommen · Demo/);
 await page.getByRole('link',{name:'Bestätigung & Ticket',exact:true}).click();await page.screenshot({path:path.join(out,`manager-confirmation-${width}.png`),fullPage:true});assert.match(await page.locator('.email-preview').innerText(),/Teamticket.pdf/);
 assert.deepEqual(errors,[]);assert.deepEqual(external,[]);await page.close();console.log(`PASS ${width}px: editor, bundle, deep duplication, publish validation, persistence, order, check-in, export, tabs, quiz; no external requests`);
}}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
