import {loadDB,saveDB,KEY} from './store.js';
import {remaining,validateName,assignFallbacks,normalName,cutoff,canJoin,whatsappLink} from './rules.js';
let db=loadDB();saveDB(db);
const app=document.querySelector('#app');
const state={eventId:'lette',step:1,name:'',email:'',method:'stripe',cart:[],city:'',bookingId:null};
const e=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const euro=n=>(n/100).toLocaleString('de-DE',{style:'currency',currency:'EUR'});
function displayEvents(){return db.events.filter(v=>v.status==='published').map(v=>({...v,rawDate:v.date,day:v.date.slice(8),month:new Date(v.date+'T12:00').toLocaleDateString('de-DE',{month:'short'}).toUpperCase(),date:new Date(v.date+'T12:00').toLocaleDateString('de-DE',{weekday:'long',day:'numeric',month:'long',year:'numeric'}),time:v.start,city:v.venue.includes('Zumbült')?'Lette':v.venue.includes('Coesfeld')?'Coesfeld':v.venue,kind:'PUB QUIZ',price:Math.min(...(v.tickets.filter(t=>t.status==='sale').length?v.tickets.filter(t=>t.status==='sale'):v.tickets).map(t=>t.price)),image:'../../images/live/freunde.jpg'}));}
let events=displayEvents();
const current=()=>events.find(ev=>ev.id===state.eventId)||events[0];
const raw=()=>db.events.find(ev=>ev.id===state.eventId);
const available=ev=>Math.max(0,Math.min(ev.capacity-db.orders.filter(o=>o.eventId===ev.id).length,ev.tickets.filter(t=>t.status==='sale').reduce((n,t)=>n+remaining(db,ev,t),0)));
const go=route=>{if(location.hash==='#'+route)render();else location.hash=route;};
const back=(route,label='Zurück zu den Quizabenden')=>`<a class="back" href="#${route}">← ${label}</a>`;
const total=()=>state.cart.reduce((n,c)=>n+(raw().tickets.find(t=>t.id===c.typeId)?.price||0),0);
function persist(){saveDB(db);}
function listing(){
  app.innerHTML=`<section class="hero"><div class="hero-copy"><span class="eyebrow">DEIN FEIERABEND KANN MEHR.</span><h1>GUTE FREUNDE.<br>KALTE DRINKS.<br><em>KLUGE KÖPFE.</em></h1><p>Ein Tisch. Euer Team. Jede Menge Gesprächsstoff.<br>Sichert euch euren nächsten Kneipenquizabend.</p><a class="primary" href="#dates">Quizabend finden <span>↓</span></a></div><div class="hero-photo"><img src="../../images/live/freunde.jpg" alt="Ein Quizteam rätselt gemeinsam an einem Tisch in der Kneipe"><div class="stamp">EUER TEAM.<strong>EUER ABEND.</strong>BIS ZU 6 KÖPFE.</div><div class="photo-note">DIE BESTEN ANTWORTEN?<br>FINDEN WIR ZUSAMMEN.<small>Echte Teams. Echte Kneipen. Der Kneipenkönig.</small></div></div></section><div class="benefits"><span><b>✓</b> Ein Ticket fürs ganze Team</span><span><b>✓</b> Direkt auf dein Handy</span><span><b>✓</b> Mit Ticketcode ins Quiz</span></div><section id="dates"><div class="section-top"><div><span class="eyebrow">RAUS AUS DEM ALLTAG</span><h2>EUER NÄCHSTER TERMIN.</h2></div><label class="filter">In deiner Nähe <select id="city" aria-label="Ort filtern"><option value="">Alle Orte</option>${[...new Set(events.map(ev=>ev.city))].map(c=>`<option ${state.city===c?'selected':''}>${c}</option>`).join('')}</select></label></div><div id="event-list">${rows()}</div></section><div class="note"><strong>Zum ersten Mal dabei?</strong> Ihr braucht kein Spezialwissen. Bringt eure Lieblingsmenschen mit. Euren Teamnamen könnt ihr später ergänzen.</div>`;
  document.querySelector('#city').onchange=ev=>{state.city=ev.target.value;document.querySelector('#event-list').innerHTML=rows();};
}
function rows(){return events.filter(ev=>!state.city||ev.city===state.city).map(ev=>`<article class="event-row"><div class="datebox"><strong>${ev.day}</strong><span>${ev.month} ’${ev.rawDate.slice(2,4)}</span></div><div><span class="event-kind">${ev.kind} · ${e(ev.city.toUpperCase())}</span><h3>${e(ev.venue)}</h3><p>${ev.date.split(',')[0]} · ${ev.time} Uhr · Teamtickets nach Wahl</p><span class="availability">${available(ev)?`Noch ${available(ev)} Teamtickets`:'Ausverkauft · Warteliste geöffnet'}</span></div><div class="price">${euro(ev.price)}<small>ab · pro Teamticket</small></div><a class="secondary" href="#event/${ev.id}">${available(ev)?'Abend entdecken ↗':'Zur Warteliste ↗'}</a></article>`).join('');}
function detail(ev){app.innerHTML=`${back('events')}<div class="detail-grid"><section><span class="eyebrow">${ev.kind} / ${e(ev.city.toUpperCase())}</span><h1>EIN ABEND.<br>EUER GANZES<br><span style="color:var(--blue)">TEAM.</span></h1><div class="facts"><span>${e(ev.date)}</span><span>${ev.time} Uhr</span></div><img class="detail-image" src="${ev.image}" alt="Atmosphäre eines Kneipenkönig-Abends"><div class="detail-copy"><h3>RÄTSELN. LACHEN. ZUSAMMEN GEWINNEN.</h3><p>Musik, Bilder, unnützes Wissen und überraschende Fragen. Schnappt euch eure Freunde und macht aus einem ganz normalen Abend euren Quizabend.</p></div><div class="detail-copy"><h3>GUT ZU WISSEN</h3><p>Wählt ein 4er-, 6er- oder anderes angebotenes Teamticket. Die tatsächliche Personenzahl wird nicht abgefragt. Im Beispiel ist der Einlass 30 Minuten vor Beginn. Getränke und Essen bestellt ihr direkt in der Kneipe. Den Tisch bekommt ihr vor Ort zugewiesen.</p></div></section><aside class="summary"><span class="availability">${available(ev)?`Noch ${available(ev)} Teamtickets verfügbar`:'Dieser Abend ist ausverkauft'}</span><h3>${e(ev.venue)}</h3><p>${e(ev.city)} · ${e(ev.date)}<br>Beginn ${ev.time} Uhr</p><div class="summary-price">${euro(ev.price)}</div><p>ab · je nach Ticketgröße</p><ul><li>Ein gemeinsamer Platz für euer Team</li><li>Digitales Ticket fürs Handy</li><li>Mit eurem Ticketcode ins Quiz</li></ul><a class="primary" href="#${available(ev)?'checkout':'waitlist'}/${ev.id}">${available(ev)?'Teamticket sichern':'Auf die Warteliste'} <span>→</span></a><p style="margin-top:14px">Beispielveranstaltung · Designvorschau</p></aside></div>`;}
function errorBox(text){const box=document.querySelector('#form-error');if(box){box.textContent=text;box.focus();}}
function cartFields(){const ev=raw();return state.cart.map((c,i)=>{const t=ev.tickets.find(t=>t.id===c.typeId);return `<div class="selection"><div><strong>${e(t.name)} · ${euro(t.price)}</strong><label for="team-${i}">Teamname ${i+1} · freiwillig</label><input id="team-${i}" data-team="${i}" maxlength="20" minlength="2" value="${e(c.team)}" placeholder="Könnt ihr später ergänzen"></div><button class="text-button" type="button" data-remove="${i}" aria-label="Teamticket ${i+1} entfernen">Entfernen</button></div>`;}).join('');}
function saveContact(){for(const key of ['name','email']){const input=document.getElementById(key);if(input)state[key]=input.value;}document.querySelectorAll('[data-team]').forEach(el=>state.cart[Number(el.dataset.team)].team=el.value);state.method=document.querySelector('input[name="method"]:checked')?.value||state.method;}
function validateCart(){const ev=raw();if(!ev||ev.status!=='published')throw Error('Dieses Event ist nicht mehr im Verkauf.');if(!state.cart.length||state.cart.length>ev.settings.maxTickets)throw Error(`Bitte 1 bis ${ev.settings.maxTickets} Teamtickets wählen.`);const seen=new Set();for(const c of state.cart){const t=ev.tickets.find(t=>t.id===c.typeId);if(!t||t.status!=='sale')throw Error('Diese Ticketart ist nicht mehr verfügbar.');c.team=validateName(db,ev.id,c.team);if(c.team&&seen.has(normalName(c.team)))throw Error('Bitte unterschiedliche Teamnamen für eure Tickets wählen.');if(c.team)seen.add(normalName(c.team));}
 const sold=db.orders.filter(o=>o.eventId===ev.id);if(sold.length+state.cart.length>ev.capacity)throw Error('Nicht mehr genügend Teamtickets verfügbar.');
 for(const t of ev.tickets){const n=state.cart.filter(c=>c.typeId===t.id).length;if(n&&(n<t.min||n>t.max||n>remaining(db,ev,t)))throw Error(`Für ${t.name} sind ${t.min} bis ${Math.min(t.max,remaining(db,ev,t))} Tickets möglich.`);}
 for(const g of ev.groups)if(sold.filter(o=>g.ticketIds.includes(o.typeId)).length+state.cart.filter(c=>g.ticketIds.includes(c.typeId)).length>g.capacity)throw Error('Das gemeinsame Tischkontingent reicht nicht aus.');
}
function checkout(){const ev=raw();if(!ev){go('events');return;}app.innerHTML=`<div class="checkout-heading">${back('event/'+ev.id,'Zum Event')}<h2>EUER ABEND BEGINNT HIER.</h2><div class="steps">${['Tickets & Teams','Deine Angaben','Bezahlen'].map((s,i)=>`<span class="${state.step===i+1?'active':''}">0${i+1} · ${s}</span>`).join('')}</div></div><div class="checkout-grid"><form id="booking-form">${checkoutStep(ev)}<p id="form-error" class="error" role="alert" tabindex="-1"></p></form><aside class="summary"><span class="eyebrow">EUER QUIZABEND</span><h3>${e(ev.venue)}</h3><p>${e(ev.date)} · ${ev.start} Uhr</p><div class="summary-row"><span>Teamtickets</span><b>${state.cart.length}</b></div><div class="summary-row"><span>Gebuchte Plätze · maximal</span><b>${state.cart.reduce((n,c)=>n+ev.tickets.find(t=>t.id===c.typeId).players,0)}</b></div><div class="total"><span>Gesamt</span><strong>${euro(total())}</strong></div><p>Ein Ticket je Team. Keine Abfrage der tatsächlichen Personenzahl.</p></aside></div>`;
 document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{saveContact();if(state.cart.length>=ev.settings.maxTickets){errorBox('Maximale Ticketzahl je Bestellung erreicht.');return;}state.cart.push({typeId:b.dataset.add,team:''});checkout();});
 document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{saveContact();state.cart.splice(Number(b.dataset.remove),1);checkout();});
 document.querySelector('#previous')?.addEventListener('click',()=>{saveContact();state.step--;checkout();});
 document.querySelector('#booking-form').onsubmit=async action=>{action.preventDefault();saveContact();try{validateCart();if(state.step<3){state.step++;checkout();focusMain();return;}
 // Serialize same-origin demo tabs. Real stock allocation belongs in a DB transaction.
 const commit=()=>{db=loadDB();validateCart();const ev=raw();if(state.method==='bar'&&!ev.cash)throw Error('Barzahlung ist für dieses Event nicht verfügbar.');const bookingId=crypto.randomUUID();for(const c of state.cart){const t=ev.tickets.find(t=>t.id===c.typeId);const id='DEMO-'+crypto.randomUUID().slice(0,8).toUpperCase();db.orders.push({id,code:id,bookingId,eventId:ev.id,typeId:t.id,ticketCapacity:t.players,team:c.team,name:state.name.trim(),email:state.email.trim(),amount:t.price,payment:state.method==='bar'?'cash-open':'confirmed',checked:false,quiz:false,joined:false,editToken:crypto.randomUUID()});}assignFallbacks(db);persist();state.bookingId=bookingId;};
 if(navigator.locks)await navigator.locks.request('kk-demo-booking',commit);else commit();go('ticket');
 }catch(err){errorBox(err.message);}};
}
function checkoutStep(ev){if(state.step===1)return `<span class="eyebrow">01 / EURE TEAMS</span><h2>WÄHLT EURE TISCHE.</h2><p>Teamnamen sind freiwillig. Bis ${ev.settings.maxTickets} Teamtickets pro Bestellung.</p>${ev.tickets.filter(t=>t.status==='sale').map(t=>`<div class="selection"><div><strong>${e(t.name)}</strong><small>Bis zu ${t.players} Plätze · ${euro(t.price)}</small></div><button class="secondary" type="button" data-add="${t.id}" ${state.cart.length>=ev.settings.maxTickets||state.cart.filter(c=>c.typeId===t.id).length>=Math.min(t.max,remaining(db,ev,t))?'disabled':''}>Hinzufügen +</button></div>`).join('')}${cartFields()}<p class="small">Namensänderungen sind bis ${ev.settings.nameCutoff} Stunden vor Quizbeginn möglich. Danach hilft dir das Veranstaltungsteam.</p><div class="form-actions"><span></span><button class="primary">Weiter →</button></div>`;
 if(state.step===2)return `<span class="eyebrow">02 / DEINE ANGABEN</span><h2>WER BUCHT FÜR EUCH?</h2><label for="name">Vor- und Nachname</label><input id="name" required maxlength="100" autocomplete="name" value="${e(state.name)}"><label for="email">E-Mail-Adresse</label><input id="email" type="email" required maxlength="254" autocomplete="email" value="${e(state.email)}"><div class="note">Lokale Vorschau – bitte Beispieldaten verwenden.</div><div class="form-actions"><button class="text-button" type="button" id="previous">← Zurück</button><button class="primary">Zur Übersicht →</button></div>`;
 return `<span class="eyebrow">03 / FAST GESCHAFFT</span><h2>EUER TICKET. EUER ABEND.</h2><p>${state.cart.length} Teamtickets · ${e(state.name)} · ${e(state.email)}</p><label class="payment"><input type="radio" name="method" value="stripe" ${state.method==='stripe'?'checked':''}><span>Karte / Apple Pay / Google Pay<small>Demo – keine Zahlung</small></span></label><label class="payment"><input type="radio" name="method" value="paypal" ${state.method==='paypal'?'checked':''}><span>PayPal · Demo</span></label>${ev.cash?`<label class="payment"><input type="radio" name="method" value="bar" ${state.method==='bar'?'checked':''}><span>Bar vor Ort<small>${euro(total())} · Zahlung und Check-in separat</small></span></label>`:''}<label class="check"><input type="checkbox" required><span>Demo mit Beispieldaten ausprobieren. Keine echte Buchung oder Abbuchung.</span></label><div class="form-actions"><button class="text-button" type="button" id="previous">← Zurück</button><button class="primary">Demo-Buchung abschließen →</button></div>`;
}
function ticket(){const list=db.orders.filter(o=>o.bookingId===state.bookingId);if(!list.length){go('events');return;}app.innerHTML=`<div class="success-head"><span class="eyebrow">LOKALE DEMO-BUCHUNG</span><h1>EUER ABEND STEHT.</h1><p>Jedes Team hat ein eigenes Ticket und einen eigenen Link zum Teamnamen.</p></div>${list.map(o=>{const ev=db.events.find(v=>v.id===o.eventId);return `<article class="ticket"><div class="ticket-left"><div class="ticket-top"><span>DER KNEIPENKÖNIG</span><span>DEMO · NICHT GÜLTIG</span></div><h2>${e(ev.venue)}</h2><p>${e(ev.date)} · ${ev.start} Uhr · Einlass ${ev.doors}<br>${e(ev.address)}</p><div class="ticket-data"><div><small>Teamname</small><strong>${e(o.team||'Noch offen')}</strong></div><div><small>Teamticket</small><strong>${o.ticketCapacity}er · bis zu ${o.ticketCapacity} Plätze</strong></div><div><small>Gebucht von</small><strong>${e(o.name)}</strong></div><div><small>Zahlung</small><strong>${o.payment==='cash-open'?'Barzahlung offen':'Demo bestätigt'}</strong></div></div><a class="text-button" href="#manage/${o.editToken}">Teamname ergänzen oder ändern →</a></div><div class="ticket-right"><img src="demo-qr.svg" alt="Demo-QR ohne Einlassberechtigung"><small>Quizcode · nur lokale Vorschau</small><code>${e(o.code)}</code></div></article>`;}).join('')}<div class="ticket-actions"><a class="primary" href="#join">Mit Ticketcode ins Quiz →</a><button class="secondary" id="print">Tickets drucken / als PDF speichern</button></div><div class="note">Druckansicht nutzbar. E-Mail-Anhang und Apple-/Google-Wallet-Pässe benötigen die Backend-Anbindung; hier wird keine Bestätigung versendet.</div>`;document.querySelector('#print').onclick=()=>window.print();}
function manage(token){const o=db.orders.find(o=>o.editToken===token);if(!o){app.innerHTML='<div class="empty"><h2>LINK NICHT GEFUNDEN.</h2><p>Bitte den Link zu deinem Teamticket verwenden.</p></div>';return;}const ev=db.events.find(v=>v.id===o.eventId),closed=Date.now()>=cutoff(ev);app.innerHTML=`<section class="join-wrap"><span class="eyebrow">${e(ev.venue)} · ${e(ev.date)}</span><h1>EUER TEAMNAME.</h1><p>${o.ticketCapacity}er Teamticket · ${e(o.code)}</p><form id="team-form"><label for="team-name">Teamname · freiwillig</label><input id="team-name" maxlength="20" minlength="2" value="${e(o.team)}" ${closed?'disabled':''}><p class="small">Änderbar bis ${new Date(cutoff(ev)).toLocaleString('de-DE',{timeZone:'Europe/Berlin'})} Uhr (Europe/Berlin).</p><p id="form-error" class="error" role="alert" tabindex="-1"></p>${closed?'<div class="note">Die Änderungsfrist ist abgelaufen. Das Veranstaltungsteam kann den Namen noch ändern.</div>':'<button class="primary">Teamname speichern →</button>'}</form><p id="saved" role="status"></p><div class="note">Demo-Link: nur in diesem Browser nutzbar. Produktiv erfolgt die Prüfung und Speicherung serverseitig.</div></section>`;document.querySelector('#team-form').onsubmit=evnt=>{evnt.preventDefault();try{db=loadDB();const row=db.orders.find(r=>r.editToken===token);const event=db.events.find(v=>v.id===row.eventId);if(Date.now()>=cutoff(event))throw Error('Die Änderungsfrist ist abgelaufen.');row.team=validateName(db,row.eventId,document.querySelector('#team-name').value,row.id);row.autoName=false;persist();document.querySelector('#saved').textContent='Teamname gespeichert.';}catch(err){errorBox(err.message);}};}
function join(){app.innerHTML=`<section class="join-wrap">${back('events')}<span class="eyebrow">VOM TICKET INS QUIZ</span><h1>EUER CODE.<br>EUER TEAM.</h1><form id="join-form"><label for="code">Ticketcode</label><input id="code" required maxlength="50" placeholder="DEMO-…" autocomplete="off"><p id="form-error" class="error" role="alert" tabindex="-1"></p><button class="primary">Team anmelden →</button></form></section>`;document.querySelector('#join-form').onsubmit=action=>{action.preventDefault();db=loadDB();const o=db.orders.find(o=>(o.code||o.id).toUpperCase()===document.querySelector('#code').value.trim().toUpperCase());if(!o){errorBox('Dieser Demo-Code wurde nicht gefunden.');return;}const ev=db.events.find(v=>v.id===o.eventId);if(!canJoin(ev,o)){errorBox('Bitte zuerst am Einlass einchecken lassen. Eine offene Barzahlung verhindert den Check-in nicht.');return;}if(!o.team){go('manage/'+o.editToken);return;}o.joined=true;persist();sessionStorage.setItem('kk-demo-player',o.id);go('lobby');};}
function lobby(){const o=db.orders.find(o=>o.id===sessionStorage.getItem('kk-demo-player'));const ev=o&&db.events.find(v=>v.id===o.eventId);if(!o||!canJoin(ev,o)||!o.joined){go('join');return;}app.innerHTML=`<section class="lobby"><div class="circle">✓</div><span class="eyebrow">TEAM ANGEMELDET · DEMO</span><h1>${e(o.team)}</h1><p>${o.ticketCapacity}er Teamticket · ${e(ev.venue)}</p><div class="note">Lokale Quiz-Lobby. Die echte Quiz-App ist noch nicht verbunden.</div><a class="secondary" href="#preparation">Quizvorbereitung ansehen</a></section>`;}
function prep(){app.innerHTML=`${back('events')}<div class="prep-head"><h1>EUER QUIZABEND.</h1><a class="secondary" href="manager.html#events">Manager öffnen →</a></div><div class="stats"><div class="stat"><strong>${db.orders.length}</strong><span>Gebuchte Teams</span></div><div class="stat"><strong>${db.orders.reduce((n,o)=>n+o.ticketCapacity,0)}</strong><span>Gebuchte Plätze · maximal</span></div></div><div class="prep-list">${db.orders.map(o=>{const ev=db.events.find(v=>v.id===o.eventId);return `<article class="registration"><div><strong>${e(o.team||'Teamname fehlt')}</strong><small>${e(ev.venue)} · ${e(o.name)}</small></div><div>${o.ticketCapacity}er Teamticket<small>${o.payment==='cash-open'?'Barzahlung offen':'Demo bestätigt'}</small></div><div>${o.joined?'Im Quiz':'Noch nicht im Quiz'}</div>${ev.settings.checkin?`<button class="secondary" data-check="${o.id}" ${o.checked?'disabled':''}>${o.checked?'Vor Ort ✓':'Demo-Check-in'}</button>`:'Check-in deaktiviert'}</article>`;}).join('')}</div>`;document.querySelectorAll('[data-check]').forEach(b=>b.onclick=()=>{db.orders.find(o=>o.id===b.dataset.check).checked=true;persist();prep();});}
function waitlist(){const ev=raw();if(!ev||!ev.waitlist){app.innerHTML='<div class="empty"><h2>KEINE WARTELISTE GEÖFFNET.</h2></div>';return;}app.innerHTML=`<section class="join-wrap">${back('event/'+ev.id,'Zum Event')}<span class="eyebrow">${e(ev.venue)}</span><h1>NOCH HOFFNUNG.</h1><p>Tragt euch für einen passenden Teamtisch ein.</p><form id="wait-form"><label for="wait-name">Dein Name</label><input id="wait-name" required maxlength="100"><label for="wait-email">E-Mail-Adresse *</label><input id="wait-email" type="email" required maxlength="254"><label for="wait-whatsapp">WhatsApp-Nummer · freiwillig</label><input id="wait-whatsapp" type="tel" autocomplete="tel" placeholder="+49 170 …"><p class="small">Mit Ländervorwahl. Über diese Nummer kann dich das Veranstaltungsteam zur Warteliste kontaktieren.</p><label for="wait-type">Gewünschtes Teamticket</label><select id="wait-type">${ev.tickets.map(t=>`<option value="${t.id}">${e(t.name)}</option>`).join('')}</select><p id="form-error" class="error" role="alert" tabindex="-1"></p><button class="primary">Auf die Demo-Warteliste →</button></form><p id="wait-message" role="status"></p></section>`;document.querySelector('#wait-form').onsubmit=action=>{action.preventDefault();const phone=document.querySelector('#wait-whatsapp').value.trim();if(phone&&!whatsappLink(phone,'')){errorBox('Bitte WhatsApp-Nummer mit Ländervorwahl eingeben, z. B. +49 170 1234567.');return;}const type=ev.tickets.find(t=>t.id===document.querySelector('#wait-type').value);db.waiters.push({id:crypto.randomUUID(),eventId:ev.id,name:document.querySelector('#wait-name').value.trim(),email:document.querySelector('#wait-email').value.trim(),whatsapp:phone,typeId:type.id,ticketCapacity:type.players,createdAt:new Date().toISOString()});persist();document.querySelector('#wait-form').hidden=true;document.querySelector('#wait-message').textContent='Ihr steht auf der lokalen Demo-Warteliste und seid im Manager sichtbar. Keine Nachricht versendet.';};}
function focusMain(){app.focus();window.scrollTo(0,0);}
function render(){db=loadDB();persist();events=displayEvents();const [route,id]=location.hash.slice(1).split('/');if(id&&db.events.some(ev=>ev.id===id)){if(state.eventId!==id){state.step=1;state.cart=[];}state.eventId=id;}switch(route){case 'event':if(current())detail(current());break;case 'checkout':state.step=1;checkout();break;case 'ticket':ticket();break;case 'manage':manage(id);break;case 'join':join();break;case 'lobby':lobby();break;case 'preparation':prep();break;case 'waitlist':waitlist();break;default:listing();}focusMain();if(route==='dates')document.querySelector('#dates')?.scrollIntoView();}
document.querySelector('#reset').onclick=()=>{state.cart=[];state.bookingId=null;state.step=1;state.name='';state.email='';go('events');};
window.addEventListener('hashchange',render);
window.addEventListener('storage',ev=>{if(ev.key===KEY){db=loadDB();events=displayEvents();if(['#lobby','#preparation'].includes(location.hash))render();}});
render();
